all:
	gcc -o program *.c interfaces/**/*.c interfaces/*.c services/**/*.c services/*.c -Wall -Wextra -pedantic -Werror -std=c11
	@clear
	./program

b:
	@clear
	gcc -o program main.c -Wall -Wextra -pedantic -Werror -std=c11
